### ISSUE TITLE
你好，请问这个是环境还是代理，环境和代理是同一个意思吗？，请问v2. 版本之后不需要环境应该怎么卸载环境。（纯菜鸡发问）

### ISSUE THREAD

**Issue by newbienoobplayer** [LauZzL/leitingzhanji#1]
如题，我2v. 版本没初始化成功过

**Comment by LauZzL** [comment]
这是加解密算法演示代码
V2版本可以下载[geek uninstaller](https://geekuninstaller.com/)卸载 git、nodejs
没初始化成功建议提供一下错误信息

**Comment by newbienoobplayer** [comment]
感谢回复，已使用geek uninstaller 把nodejs和Gits卸载
无论是 v2.5,v2.4,v2.1 都依旧初始化失败，
![image](https://github.com/user-attachments/assets/b3593ae6-a7ea-44b0-9f32-c4029a1b18e3)
![image](https://github.com/user-attachments/assets/e4c44c63-e4b1-420a-8c40-a3e76635b917)
![image](https://github.com/user-attachments/assets/734dd7ac-21e3-4e01-bc3b-9e2c99bac303)








v2.6无法点击初始化（按钮没亮）
![image](https://github.com/user-attachments/assets/3b5e4eb1-f0b7-44fa-adc5-bd2b0222caf7)

请问应该怎么提供错误信息

**Comment by LauZzL** [comment]
如果你是海外用户可能无法使用 并且在昨日已经禁止了所有用户访问 该程序不再更新

**Comment by newbienoobplayer** [comment]
了解，感谢你的帮助
